#!/usr/bin/env bash

set -e

PROJ=consul-tags
PKG_SRC=${PKG_SRC:-.}

env|sort

# Get rid of existing binaries
rm -f bin/${PROJ}*

# Build 386 amd64 binaries
OS_PLATFORM_ARG=(linux)
OS_ARCH_ARG=(amd64)
if [ "$1" == "--all" ]; then
  OS_PLATFORM_ARG=(linux darwin windows freebsd openbsd)
  OS_ARCH_ARG=(386 amd64)
elif [ "$1" == "--ci" ]; then
  OS_PLATFORM_ARG=(linux darwin windows)
  OS_ARCH_ARG=(386 amd64)
fi
for OS in ${OS_PLATFORM_ARG[@]}; do
  for ARCH in ${OS_ARCH_ARG[@]}; do
    echo "Building binary for $OS/$ARCH..."
    #    GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build -ldflags "-s -w" -o "bin/${PROJ}_$OS-$ARCH" $PKG_SRC && \
    #      ls -l "bin/${PROJ}_$OS-$ARCH" && \
    #      upx --brute "bin/${PROJ}_$OS-$ARCH" && \
    #      ls -l "bin/${PROJ}_$OS-$ARCH"
    GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build -ldflags "-s -w" -o "bin/${PROJ}_$OS-$ARCH" $PKG_SRC
    if [ "$OS" == "linux" ]; then
      ls -l "bin/${PROJ}_$OS-$ARCH" && \
      # upx "bin/${PROJ}_$OS-$ARCH" && \
      ls -l "bin/${PROJ}_$OS-$ARCH" && echo
    fi
    if [ ! -f "bin/${PROJ}_$OS-$ARCH" ]; then
      exit 9
    fi
  done
done

# Build arm binaries
if [ "$1" == "--all" ]; then
  OS_PLATFORM_ARG=(linux)
  OS_ARCH_ARG=(arm arm64)
  for OS in ${OS_PLATFORM_ARG[@]}; do
    for ARCH in ${OS_ARCH_ARG[@]}; do
      echo "Building binary for $OS/$ARCH..."
      #      GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build -ldflags "-s -w" -o "bin/${PROJ}_$OS-$ARCH" $PKG_SRC && \
      #      ls -l "bin/${PROJ}_$OS-$ARCH" && \
      #      upx --brute "bin/${PROJ}_$OS-$ARCH" && \
      #      ls -l "bin/${PROJ}_$OS-$ARCH"
      GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build -ldflags "-s -w" -v -o "bin/${PROJ}_$OS-$ARCH" $PKG_SRC && \
      ls -l "bin/${PROJ}_$OS-$ARCH" && echo
    done
  done
elif [ "$1" == "--ci" ]; then
  :
else
  :
fi

if [ "$1" != "--ci" ]; then
  echo "Building default binary"
  ARCH=amd64
  OS=darwin
  GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build -ldflags "-s -w" -o "bin/${PROJ}" $PKG_SRC
fi



chmod +x bin/${PROJ}*
cd bin; tar czf ../${PROJ}.tgz ${PROJ}*; cd ..



if [ "$1" != "--ci" ]; then
  echo "Publish linux-amd64 copy to s3 [paused]..."
  [ -f /tmp/$PROJ ] && rm -f /tmp/$PROJ
  [ -f /tmp/$PROJ.gz ] && rm -f /tmp/$PROJ.gz
  cp bin/${PROJ}_linux-amd64 /tmp/$PROJ
  gzip /tmp/$PROJ && ls -la /tmp/${PROJ}* && \
  : #aws s3 cp /tmp/$PROJ.gz s3://hedzr-tools/devops.gz
fi


ls -la
